export default {
  driverImage: require('../../assets/driver.png'),
  passengerImage: require('../../assets/passengerImage.jpg'),
  suzuki_logo: require('../../assets/Cars/suzuki-logo.png'),
  toyota_logo: require('../../assets/Cars/toyota-logo.png'),
  honda_logo: require('../../assets/Cars/honda-logo.png'),
  hyundai_logo: require('../../assets/Cars/hyundai-logo.png'),
  tata_logo: require('../../assets/Cars/tata-logo.png'),
  bajaj_logo: require('../../assets/Cars/bajaj-logo.png'),
  celerio: require('../../assets/Car-image/Selerio-Blue.png'),
  swift: require('../../assets/Car-image/Swift-red.jpeg'),
  baleno: require('../../assets/Car-image/Baleno-blue.jpeg'),
  'wagon r': require('../../assets/Car-image/WagonR-grey.jpeg'),
  dzire: require('../../assets/Car-image/Dzire-articwhite.jpeg'),
  alto: require('../../assets/Car-image/Alto800-red.jpeg'),
  ertiga: require('../../assets/Car-image/Ertiga-red.jpeg'),
  xl6: require('../../assets/Car-image/XL6-blue.jpeg'),
  'vitara brezza': require('../../assets/Car-image/Brezza-red.jpeg'),
  'grand i10': require('../../assets/Car-image/Grandi10-polarwhite.jpeg'),
  i20: require('../../assets/Car-image/i20-red.jpeg'),
  venue: require('../../assets/Car-image/Venue-red.jpeg'),
  creta: require('../../assets/Car-image/Creta-black.jpeg'),
  verna: require('../../assets/Car-image/Verna-black.jpeg'),
  aura: require('../../assets/Car-image/Aura-black.jpeg'),
  tucson: require('../../assets/Car-image/Tucson-white.jpeg'),
  altroz: require('../../assets/Car-image/Altroz-golden.jpeg'),
  tiago: require('../../assets/Car-image/Tiago-blue.jpeg'),
  tigor: require('../../assets/Car-image/Tigor-meteorbronze.jpeg'),
  nexon: require('../../assets/Car-image/Nexon-purple.jpeg'),
  harrier: require('../../assets/Car-image/Harrier-Yellow.jpeg'),
  safari: require('../../assets/Car-image/Safari-black.jpeg'),
  city: require('../../assets/Car-image/City-red.jpeg'),
  amaze: require('../../assets/Car-image/Amaze-black.jpeg'),
  jazz: require('../../assets/Car-image/Jazz-red.jpeg'),
  'wr-v': require('../../assets/Car-image/WRV-white.jpeg'),
  civic: require('../../assets/Car-image/WRV-white.jpeg'),
  'cr-v': require('../../assets/Car-image/CRV-white.jpeg'),
  mapCurMarker: require('../../assets/MapImages/Oval.png'),
  mapDestMarker: require('../../assets/MapImages/greenMarker.png'),
  mapGetCurLoc: require('../../assets/MapImages/greenIndicator.png'),
  splash: require('../../assets/Blue-PNG.png'),
};
